/*
 * This source file was generated by the Gradle 'init'
 * 
 * The application has been tested with a real key and works as expected.
 * 
 * The assignment requires the app to make requests every 5 seconds; however,
 * this frequency exceeds the free tier limit imposed by Alpha Vantage, which
 * allows only 5 requests per minute (one request every 12 seconds).
 * 
 * After several tests and reviewing Alpha Vantage’s official documentation,
 * I adjusted the request interval to comply with their rate limits to avoid errors.
 * 
 * I initially faced similar rate limit issues with Yahoo Finance’s unofficial API,
 * but after switching to Alpha Vantage with a valid API key and following their limits,
 * the application runs well.
 */
package org.example;

import org.json.JSONObject;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;
import java.util.Calendar;
import java.util.LinkedList;
import java.util.Queue;

public class App {
    private static final String API_KEY = "API_KEY_HERE";  // Replace the placeholder with Actual Alpha Vantage API key before running

    private static final String SYMBOL = "DIA";  // ETF symbol tracking DJIA
    private static final Queue<String> stockDataQueue = new LinkedList<>();
    private static final int MAX_QUEUE_SIZE = 100;

    public static void main(String[] args) {
        System.out.println("Starting Dow Jones stock price fetcher using Alpha Vantage...");

        // Fetch every 60 seconds to respect free tier limits (5 calls per minute)
        final int fetchIntervalSeconds = 60;

        Runnable fetchTask = () -> {
            try {
                fetchAndStoreStockPrice();
            } catch (Exception e) {
                System.err.println("Error during fetch: " + e.getMessage());
            }
        };

        // To Schedule the task repeatedly with delay
        while (true) {
            fetchTask.run();
            try {
                Thread.sleep(fetchIntervalSeconds * 1000L);
            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
                System.out.println("Fetcher interrupted, exiting...");
                break;
            }
        }
    }

    private static void fetchAndStoreStockPrice() throws Exception {
        String urlString = String.format(
            "https://www.alphavantage.co/query?function=GLOBAL_QUOTE&symbol=%s&apikey=%s",
            SYMBOL, API_KEY);

        URL url = new URL(urlString);
        HttpURLConnection conn = (HttpURLConnection) url.openConnection();
        conn.setRequestMethod("GET");

        int responseCode = conn.getResponseCode();
        if (responseCode != 200) {
            throw new Exception("HTTP error code: " + responseCode);
        }

        BufferedReader in = new BufferedReader(new InputStreamReader(conn.getInputStream()));
        StringBuilder responseStrBuilder = new StringBuilder();
        String inputLine;
        while ((inputLine = in.readLine()) != null) {
            responseStrBuilder.append(inputLine);
        }
        in.close();

        JSONObject json = new JSONObject(responseStrBuilder.toString());
        JSONObject globalQuote = json.optJSONObject("Global Quote");
        if (globalQuote == null || globalQuote.isEmpty()) {
            System.err.println("No data received for symbol: " + SYMBOL);
            return;
        }

        String priceStr = globalQuote.optString("05. price");
        if (priceStr.isEmpty()) {
            System.err.println("Price data missing in response.");
            return;
        }

        double price = Double.parseDouble(priceStr);
        String timestamp = Calendar.getInstance().getTime().toString();

        synchronized (stockDataQueue) {
            if (stockDataQueue.size() >= MAX_QUEUE_SIZE) {
                stockDataQueue.poll(); // Remove oldest
            }
            stockDataQueue.add("Price: " + price + ", Timestamp: " + timestamp);
        }

        System.out.println("Fetched: Price: " + price + ", Timestamp: " + timestamp);
    }
}
